# coding: utf-8

"""
    Legacy model dictionaries

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
from inspect import getfullargspec
import json
import pprint
import re  # noqa: F401
from pydantic import BaseModel, ConfigDict, Field, StrictStr, ValidationError, field_validator
from typing import Dict, List, Optional
from legacy_model_dict_client.models.legacy_model import LegacyModel
from legacy_model_dict_client.models.nested_model import NestedModel
from typing import Union, Any, List, Set, TYPE_CHECKING, Optional, Dict, ClassVar
from typing_extensions import Literal, Self
from pydantic import Field


def _is_generated_model(value: Any) -> bool:
    to_dict = getattr(value, "to_dict", None)
    generated_to_dict = getattr(
        type(value), "_legacy_model_to_dict_impl", None
    )
    # Exact method identity preserves zero-argument subclass overrides.
    return (
        callable(to_dict)
        and generated_to_dict is not None
        and generated_to_dict is getattr(to_dict, "__func__", None)
    )


def _to_legacy_value(value: Any, serialize: bool) -> Any:
    if isinstance(value, list):
        return [_to_legacy_value(item, serialize) for item in value]
    if isinstance(value, dict):
        return {
            key: _to_legacy_value(item, serialize)
            for key, item in value.items()
        }

    to_dict = getattr(value, "to_dict", None)
    if _is_generated_model(value) and callable(to_dict):
        return to_dict(serialize=serialize)
    if callable(to_dict):
        return to_dict()
    return value


def _to_openapi_value(value: Any) -> Any:
    if isinstance(value, list):
        return [_to_openapi_value(item) for item in value]
    if isinstance(value, dict):
        return {key: _to_openapi_value(item) for key, item in value.items()}

    to_openapi_dict = getattr(value, "_to_openapi_dict", None)
    if _is_generated_model(value) and callable(to_openapi_dict):
        return to_openapi_dict()

    to_dict = getattr(value, "to_dict", None)
    if callable(to_dict):
        return to_dict()
    return value


ANYOFMODEL_ANY_OF_SCHEMAS = ["Dict[str, NestedModel]", "LegacyModel", "List[NestedModel]", "str"]

class AnyOfModel(BaseModel):
    """
    AnyOfModel
    """

    # data type: LegacyModel
    anyof_schema_1_validator: Optional[LegacyModel] = None
    # data type: List[NestedModel]
    anyof_schema_2_validator: Optional[List[NestedModel]] = None
    # data type: Dict[str, NestedModel]
    anyof_schema_3_validator: Optional[Dict[str, NestedModel]] = None
    # data type: str
    anyof_schema_4_validator: Optional[StrictStr] = None
    if TYPE_CHECKING:
        actual_instance: Optional[Union[Dict[str, NestedModel], LegacyModel, List[NestedModel], str]] = None
    else:
        actual_instance: Any = None
    any_of_schemas: Set[str] = { "Dict[str, NestedModel]", "LegacyModel", "List[NestedModel]", "str" }

    model_config = {
        "validate_assignment": True,
        "protected_namespaces": (),
    }

    def __init__(self, *args, **kwargs) -> None:
        if args:
            if len(args) > 1:
                raise ValueError("If a position argument is used, only 1 is allowed to set `actual_instance`")
            if kwargs:
                raise ValueError("If a position argument is used, keyword arguments cannot be used.")
            super().__init__(actual_instance=args[0])
        else:
            super().__init__(**kwargs)

    @field_validator('actual_instance')
    def actual_instance_must_validate_anyof(cls, v):
        instance = AnyOfModel.model_construct()
        error_messages = []
        # validate data type: LegacyModel
        if not isinstance(v, LegacyModel):
            error_messages.append(f"Error! Input type `{type(v)}` is not `LegacyModel`")
        else:
            return v

        # validate data type: List[NestedModel]
        try:
            instance.anyof_schema_2_validator = v
            return v
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # validate data type: Dict[str, NestedModel]
        try:
            instance.anyof_schema_3_validator = v
            return v
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # validate data type: str
        try:
            instance.anyof_schema_4_validator = v
            return v
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        if error_messages:
            # no match
            raise ValueError("No match found when setting the actual_instance in AnyOfModel with anyOf schemas: Dict[str, NestedModel], LegacyModel, List[NestedModel], str. Details: " + ", ".join(error_messages))
        else:
            return v

    @classmethod
    def from_dict(cls, obj: Dict[str, Any]) -> Self:
        return cls.from_json(json.dumps(obj))

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Returns the object represented by the json string"""
        instance = cls.model_construct()
        error_messages = []
        # anyof_schema_1_validator: Optional[LegacyModel] = None
        try:
            instance.actual_instance = LegacyModel.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
             error_messages.append(str(e))
        # deserialize data into List[NestedModel]
        try:
            # validation
            instance.anyof_schema_2_validator = json.loads(json_str)
            # assign value to actual_instance
            instance.actual_instance = instance.anyof_schema_2_validator
            return instance
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into Dict[str, NestedModel]
        try:
            # validation
            instance.anyof_schema_3_validator = json.loads(json_str)
            # assign value to actual_instance
            instance.actual_instance = instance.anyof_schema_3_validator
            return instance
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into str
        try:
            # validation
            instance.anyof_schema_4_validator = json.loads(json_str)
            # assign value to actual_instance
            instance.actual_instance = instance.anyof_schema_4_validator
            return instance
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))

        if error_messages:
            # no match
            raise ValueError("No match found when deserializing the JSON string into AnyOfModel with anyOf schemas: Dict[str, NestedModel], LegacyModel, List[NestedModel], str. Details: " + ", ".join(error_messages))
        else:
            return instance

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        if hasattr(self.actual_instance, "to_json") and callable(self.actual_instance.to_json):
            return self.actual_instance.to_json()
        else:
            return json.dumps(self.actual_instance)

    def to_dict(self, serialize: bool = False) -> Any:
        """Returns the public or wire representation of the actual instance"""
        if self.actual_instance is None:
            return None

        return _to_legacy_value(self.actual_instance, serialize)

    # Record the generated method so inherited implementations can be
    # distinguished from subclass overrides and foreign objects.
    _legacy_model_to_dict_impl: ClassVar[object] = to_dict

    def _to_openapi_dict(self) -> Any:
        """Returns the wire representation of the actual instance"""
        if self.actual_instance is None:
            return None

        return _to_openapi_value(self.actual_instance)

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.model_dump())


