# coding: utf-8

"""
    Legacy model dictionaries

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import AliasChoices, BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from legacy_model_dict_client.models.nested_model import NestedModel
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    _LegacyModel_var_continue_public_type = Optional[StrictStr]


def _is_generated_model(value: Any) -> bool:
    to_dict = getattr(value, "to_dict", None)
    generated_to_dict = getattr(
        type(value), "_legacy_model_to_dict_impl", None
    )
    # Exact method identity preserves zero-argument subclass overrides.
    return (
        callable(to_dict)
        and generated_to_dict is not None
        and generated_to_dict is getattr(to_dict, "__func__", None)
    )


def _to_legacy_value(value: Any, serialize: bool) -> Any:
    if isinstance(value, list):
        return [_to_legacy_value(item, serialize) for item in value]
    if isinstance(value, dict):
        return {
            key: _to_legacy_value(item, serialize)
            for key, item in value.items()
        }

    to_dict = getattr(value, "to_dict", None)
    if _is_generated_model(value) and callable(to_dict):
        return to_dict(serialize=serialize)
    if callable(to_dict):
        return to_dict()
    return value


def _to_openapi_value(value: Any) -> Any:
    if isinstance(value, list):
        return [_to_openapi_value(item) for item in value]
    if isinstance(value, dict):
        return {key: _to_openapi_value(item) for key, item in value.items()}

    to_openapi_dict = getattr(value, "_to_openapi_dict", None)
    if _is_generated_model(value) and callable(to_openapi_dict):
        return to_openapi_dict()

    to_dict = getattr(value, "to_dict", None)
    if callable(to_dict):
        return to_dict()
    return value


class LegacyModel(BaseModel):
    """
    LegacyModel
    """ # noqa: E501
    inherited_value: Optional[StrictStr] = Field(default=None, validation_alias=AliasChoices("inheritedValue", "inherited_value"), serialization_alias="inheritedValue", alias="inheritedValue")
    var_continue: Optional[StrictStr] = Field(default=None, validation_alias=AliasChoices("continue", "_continue"), serialization_alias="continue", alias="_continue")
    renamed: Optional[StrictStr] = Field(default=None, validation_alias=AliasChoices("ordinary", "renamed"), serialization_alias="ordinary")
    read_only_value: Optional[StrictStr] = Field(default=None, validation_alias=AliasChoices("readOnlyValue", "read_only_value"), serialization_alias="readOnlyValue", alias="readOnlyValue")
    nested: Optional[NestedModel] = None
    nested_list: Optional[List[NestedModel]] = Field(default=None, validation_alias=AliasChoices("nestedList", "nested_list"), serialization_alias="nestedList", alias="nestedList")
    nested_map: Optional[Dict[str, NestedModel]] = Field(default=None, validation_alias=AliasChoices("nestedMap", "nested_map"), serialization_alias="nestedMap", alias="nestedMap")
    nullable_value: Optional[StrictStr] = Field(default=None, validation_alias=AliasChoices("nullableValue", "nullable_value"), serialization_alias="nullableValue", alias="nullableValue")
    default_value: Optional[StrictStr] = Field(default='default', validation_alias=AliasChoices("defaultValue", "default_value"), serialization_alias="defaultValue", alias="defaultValue")
    __properties: ClassVar[List[str]] = ["inheritedValue", "continue", "ordinary", "readOnlyValue", "nested", "nestedList", "nestedMap", "nullableValue", "defaultValue"]

    model_config = ConfigDict(
        validate_by_name=False,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    # Forwarding properties must be installed after forward annotations are
    # resolved so their public names cannot shadow annotation imports.
    # https://docs.pydantic.dev/2.12/api/base_model/#pydantic.main.BaseModel.__pydantic_on_complete__
    @classmethod
    def __pydantic_on_complete__(cls) -> None:
        super().__pydantic_on_complete__()
        setattr(
            cls,
            "_continue",
            property(
                lambda self: self.var_continue,
                lambda self, value: setattr(
                    self,
                    "var_continue",
                    value,
                ),
            ),
        )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        if _is_generated_model(self):
            return json.dumps(to_jsonable_python(self._to_openapi_dict()))
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of LegacyModel from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self, serialize: bool = False) -> Dict[str, Any]:
        """Return all declared model fields using public or wire names."""
        return {
            ("inheritedValue" if serialize else "inherited_value"): _to_legacy_value(self.inherited_value, serialize),
            ("continue" if serialize else "_continue"): _to_legacy_value(self.var_continue, serialize),
            ("ordinary" if serialize else "renamed"): _to_legacy_value(self.renamed, serialize),
            ("readOnlyValue" if serialize else "read_only_value"): _to_legacy_value(self.read_only_value, serialize),
            ("nested" if serialize else "nested"): _to_legacy_value(self.nested, serialize),
            ("nestedList" if serialize else "nested_list"): _to_legacy_value(self.nested_list, serialize),
            ("nestedMap" if serialize else "nested_map"): _to_legacy_value(self.nested_map, serialize),
            ("nullableValue" if serialize else "nullable_value"): _to_legacy_value(self.nullable_value, serialize),
            ("defaultValue" if serialize else "default_value"): _to_legacy_value(self.default_value, serialize),
        }

    # Record the generated method so inherited implementations can be
    # distinguished from subclass overrides and foreign objects.
    _legacy_model_to_dict_impl: ClassVar[object] = to_dict

    def _to_openapi_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        """
        excluded_fields: Set[str] = set([
            "read_only_value",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of nested
        if self.nested:
            _dict['nested'] = _to_openapi_value(self.nested)
        # override the default output from pydantic by calling `to_dict()` of each item in nested_list (list)
        _items = []
        if self.nested_list:
            for _item_nested_list in self.nested_list:
                if _item_nested_list:
                    _items.append(_to_openapi_value(_item_nested_list))
            _dict['nestedList'] = _items
        # override the default output from pydantic by calling `to_dict()` of each value in nested_map (dict)
        _field_dict = {}
        if self.nested_map:
            for _key_nested_map in self.nested_map:
                if self.nested_map[_key_nested_map]:
                    _field_dict[_key_nested_map] = _to_openapi_value(self.nested_map[_key_nested_map])
            _dict['nestedMap'] = _field_dict
        # set to None if nullable_value (nullable) is None
        # and model_fields_set contains the field
        if self.nullable_value is None and "nullable_value" in self.model_fields_set:
            _dict['nullableValue'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of LegacyModel from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        obj = dict(obj)
        if "inheritedValue" not in obj and "inherited_value" in obj:
            obj["inheritedValue"] = obj["inherited_value"]
        obj.pop("inherited_value", None)
        if "continue" not in obj and "_continue" in obj:
            obj["continue"] = obj["_continue"]
        obj.pop("_continue", None)
        if "ordinary" not in obj and "renamed" in obj:
            obj["ordinary"] = obj["renamed"]
        obj.pop("renamed", None)
        if "readOnlyValue" not in obj and "read_only_value" in obj:
            obj["readOnlyValue"] = obj["read_only_value"]
        obj.pop("read_only_value", None)
        if "nestedList" not in obj and "nested_list" in obj:
            obj["nestedList"] = obj["nested_list"]
        obj.pop("nested_list", None)
        if "nestedMap" not in obj and "nested_map" in obj:
            obj["nestedMap"] = obj["nested_map"]
        obj.pop("nested_map", None)
        if "nullableValue" not in obj and "nullable_value" in obj:
            obj["nullableValue"] = obj["nullable_value"]
        obj.pop("nullable_value", None)
        if "defaultValue" not in obj and "default_value" in obj:
            obj["defaultValue"] = obj["default_value"]
        obj.pop("default_value", None)
        obj.pop("var_continue", None)

        _obj = cls.model_validate({
            "inheritedValue": obj.get("inheritedValue"),
            "continue": obj.get("continue"),
            "ordinary": obj.get("ordinary"),
            "readOnlyValue": obj.get("readOnlyValue"),
            "nested": NestedModel.from_dict(obj["nested"]) if obj.get("nested") is not None else None,
            "nestedList": [NestedModel.from_dict(_item) for _item in obj["nestedList"]] if obj.get("nestedList") is not None else None,
            "nestedMap": dict(
                (_k, NestedModel.from_dict(_v))
                for _k, _v in obj["nestedMap"].items()
            )
            if obj.get("nestedMap") is not None
            else None,
            "nullableValue": obj.get("nullableValue"),
            "defaultValue": obj.get("defaultValue") if obj.get("defaultValue") is not None else 'default'
        })
        return _obj

    if TYPE_CHECKING:

        @property
        def _continue(self) -> _LegacyModel_var_continue_public_type:
            return self.var_continue

        @_continue.setter
        def _continue(self, value: _LegacyModel_var_continue_public_type) -> None:
            self.var_continue = value


