# coding: utf-8

"""
    Legacy model dictionaries

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python


def _is_generated_model(value: Any) -> bool:
    to_dict = getattr(value, "to_dict", None)
    generated_to_dict = getattr(
        type(value), "_legacy_model_to_dict_impl", None
    )
    # Exact method identity preserves zero-argument subclass overrides.
    return (
        callable(to_dict)
        and generated_to_dict is not None
        and generated_to_dict is getattr(to_dict, "__func__", None)
    )


def _to_legacy_value(value: Any, serialize: bool) -> Any:
    if isinstance(value, list):
        return [_to_legacy_value(item, serialize) for item in value]
    if isinstance(value, dict):
        return {
            key: _to_legacy_value(item, serialize)
            for key, item in value.items()
        }

    to_dict = getattr(value, "to_dict", None)
    if _is_generated_model(value) and callable(to_dict):
        return to_dict(serialize=serialize)
    if callable(to_dict):
        return to_dict()
    return value


def _to_openapi_value(value: Any) -> Any:
    if isinstance(value, list):
        return [_to_openapi_value(item) for item in value]
    if isinstance(value, dict):
        return {key: _to_openapi_value(item) for key, item in value.items()}

    to_openapi_dict = getattr(value, "_to_openapi_dict", None)
    if _is_generated_model(value) and callable(to_openapi_dict):
        return to_openapi_dict()

    to_dict = getattr(value, "to_dict", None)
    if callable(to_dict):
        return to_dict()
    return value


class NestedModel(BaseModel):
    """
    NestedModel
    """ # noqa: E501
    camel_case: Optional[StrictStr] = Field(default=None, alias="camelCase")
    nested_read_only_value: Optional[StrictStr] = Field(default=None, alias="nestedReadOnlyValue")
    __properties: ClassVar[List[str]] = ["camelCase", "nestedReadOnlyValue"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        if _is_generated_model(self):
            return json.dumps(to_jsonable_python(self._to_openapi_dict()))
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of NestedModel from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self, serialize: bool = False) -> Dict[str, Any]:
        """Return all declared model fields using public or wire names."""
        return {
            ("camelCase" if serialize else "camel_case"): _to_legacy_value(self.camel_case, serialize),
            ("nestedReadOnlyValue" if serialize else "nested_read_only_value"): _to_legacy_value(self.nested_read_only_value, serialize),
        }

    # Record the generated method so inherited implementations can be
    # distinguished from subclass overrides and foreign objects.
    _legacy_model_to_dict_impl: ClassVar[object] = to_dict

    def _to_openapi_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        """
        excluded_fields: Set[str] = set([
            "nested_read_only_value",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of NestedModel from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "camelCase": obj.get("camelCase"),
            "nestedReadOnlyValue": obj.get("nestedReadOnlyValue")
        })
        return _obj


